### ISSUE TITLE
Starlark Support

### ISSUE THREAD

**Issue by ColdHeat** [zeaphoo/likepy#1]
I stumbled upon this library while looking around for a way to run Starlark scripts in Python. I ended up writing Python bindings for starlark-go. I know that the Starlark support in likepy is still progressing but perhaps my bindings could be useful to you as well: https://github.com/ColdHeat/pystarlark

**Comment by zeaphoo** [comment]
Thanks for interesting on this project, and providing helps.  Likepy try convert some python like programming language  to python bytecode safely. Since it's just a part time project,  the progressing is a bit slow.
